dist: trusty
sudo: required
before_install:
- sudo apt-get install build-essential debhelper devscripts dh-make lintian
- gem install asciidoctor
install: true
before_script: echo -e $GPG_SECRET | gpg --import
script: make deb
deploy:
  provider: script
  script: dput ppa:cs50/ppa *.changes
  skip_cleanup: true
  on:
    branch: launchpad
notifications:
  slack:
    secure: ISOGlNSGXOrMBrKTnjTWQXVjjoBn78++xF1mUv/PYZxn3J4L4WpybLLjAuBENsD7YeHSaXUnSbIV5mDzlx5Q1cyrS+auGOHqi5xGV01zNBB1Fig1SkUf7zJS8KyjiPKyi+DexnTt1BY4xaA1uGzq9hoGZEPXKHNlz4v1I6f6fHQ=
